using QuestPDF.Fluent;
using QuestPDF.Infrastructure;

namespace Medicare.Utility
{
    public class PrescriptionDocument : IDocument
    {
        private readonly string _prescriptionContent;

        public PrescriptionDocument(string prescriptionContent)
        {
            _prescriptionContent = prescriptionContent;
        }
        public DocumentMetadata GetMetadata() => DocumentMetadata.Default;
        public void Compose(IDocumentContainer container)
        {
            container.Page(page =>
            {
                page.Margin(20);

                page.Header().Element(ComposeHeader);

                page.Content().PaddingVertical(10).Column(col =>
                {
                    // Prescription Content (from Quill)
                    col.Item().Element(ComposePrescriptionContent);
                });

                page.Footer()
                    .AlignCenter()
                    .Text(x =>
                    {
                        x.Span("Generated by MediCare System").FontSize(10);
                    });
            });
        }

        private void ComposeHeader(IContainer container)
        {
            container.Row(row =>
            {
                // Clinic Details (left)
                row.RelativeItem().Column(col =>
                {
                    col.Item().Text("MediCare").Bold().FontSize(16);
                    col.Item().Text("Clinic Address, City, State").FontSize(11);
                    col.Item().Text("Phone: +91-1234567890").FontSize(11);
                    col.Item().Text("Email: clinic@example.com").FontSize(11);
                });

                // Doctor Details (right)
                row.RelativeItem().AlignRight().Column(col =>
                {
                    col.Item().Text("Dr. John Doe").Bold().FontSize(14);
                    col.Item().Text("MBBS, MD - General Physician").FontSize(11);
                    col.Item().Text("Reg. No: 123456").FontSize(11);
                    col.Item().Text("Contact: +91-9876543210").FontSize(11);
                });
            });
        }

        private void ComposePrescriptionContent(IContainer container)
        {
            container.Column(col =>
            {
                col.Item().Text("Prescription").Bold().FontSize(14).Underline().AlignCenter();
                col.Item().PaddingTop(10).Element(x =>
                {
                    // Convert Quill HTML → Plain Text (basic)  
                    x.Text(_prescriptionContent).FontSize(12);
                });
            });
        }
    }
}
